name: CI

on:
  push:
    branches:
      - main

permissions:
  contents: write  # Ensure workflow has write access

jobs:
  deploy:
    runs-on: ubuntu-latest  # Or adjust runner OS if needed

    steps:
      - uses: actions/checkout@v3

      - name: Configure Git Credentials
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - name: Set up Python (choose a supported version)
        uses: actions/setup-python@v4
        with:
          python-version: '3.X'  # Replace X with a supported version (e.g., 3.8, 3.9, 3.10)

      - name: Install dependencies
        run: |
          python -m pip install mkdocs mkdocs-material  # Install both MkDocs and Material theme

      - name: Cache MkDocs dependencies (optional)
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-mkdocs-${{ hashFiles('mkdocs.yml') }}  # Cache key based on OS, MkDocs version, and MkDocs config changes
          restore-keys: |
            ${{ runner.os }}-mkdocs-

      - name: Build documentation (with echo for debugging)
        run: |
          echo "Building MkDocs documentation..."
          mkdocs build  # Build the documentation locally (for debugging)
          echo "Documentation built successfully."

      - name: Deploy documentation (with error capture)
        run: |
          echo "Deploying documentation..."
          mkdocs gh-deploy --force || true  # Capture errors but continue execution (for logging)
          echo "Deployment complete."

