name: CI

on:
  push:
    branches:
      - master
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure Git Credentials
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - uses: actions/setup-python@v3
        with:
          python-version: 'latest'  # Use the latest available Python version

      - name: Install dependencies
        run: |
          python -m pip install mkdocs mkdocs-material  # Install both MkDocs and Material theme

      - name: Cache MkDocs dependencies (optional)
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip  # Cache pip dependencies
          key: ${{ runner.os }}-mkdocs-${{ hashFiles('mkdocs.yml') }}  # Cache key based on OS, MkDocs version, and MkDocs config changes
          restore-keys: |
            ${{ runner.os }}-mkdocs-

      - name: Build and deploy documentation
        run: mkdocs gh-deploy --force
